package com.java2okf.cli;

import com.fasterxml.jackson.databind.JsonNode;
import com.java2okf.validation.BundleStatistics;
import picocli.CommandLine.Command;
import picocli.CommandLine.Model.CommandSpec;
import picocli.CommandLine.Option;
import picocli.CommandLine.Spec;

import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.Callable;

/**
 * {@code java2okf stats}: prints entity, relationship, and document statistics of a bundle.
 */
@Command(name = "stats", mixinStandardHelpOptions = true,
        description = "Print statistics of an OKF bundle generated by Java2OKF.",
        footer = {"", "Exit codes: 0 = success, 2 = bundle or _metadata/analysis.json not found."})
public class StatsCommand implements Callable<Integer> {

    @Spec
    private CommandSpec spec;

    @Option(names = {"-b", "--bundle"}, required = true, paramLabel = "DIR", description = "Bundle directory.")
    private Path bundle;

    @Override
    public Integer call() {
        PrintWriter out = spec.commandLine().getOut();
        PrintWriter err = spec.commandLine().getErr();
        if (!Files.isDirectory(bundle)) {
            err.println("Bundle directory not found: " + bundle);
            err.flush();
            return ExitCodes.CONFIG_ERROR;
        }
        BundleStatistics statistics = BundleStatistics.collect(bundle);
        if (statistics.metadata().isEmpty()) {
            err.println("No _metadata/analysis.json in " + bundle + "; was it generated by Java2OKF?");
            err.flush();
            return ExitCodes.CONFIG_ERROR;
        }
        JsonNode m = statistics.metadata().get();
        JsonNode byType = m.path("relationshipsByType");

        out.println("Java2OKF Statistics");
        out.println("===================");
        out.println();
        out.println("Project: " + m.path("project").asText() + " (" + m.path("tool").asText() + " "
                + m.path("version").asText() + ", OKF " + m.path("okfVersion").asText() + ")");
        out.println();
        section(out, "Entities");
        row(out, "Packages", m.path("packages").asLong());
        row(out, "Classes", m.path("classes").asLong());
        row(out, "Interfaces", m.path("interfaces").asLong());
        row(out, "Enums", m.path("enums").asLong());
        row(out, "Records", m.path("records").asLong());
        row(out, "Annotations", m.path("annotations").asLong());
        row(out, "Methods", m.path("methods").asLong());
        row(out, "Constructors", m.path("constructors").asLong());
        row(out, "Fields", m.path("fields").asLong());
        out.println();
        section(out, "Relationships");
        row(out, "Extends", byType.path("EXTENDS").asLong());
        row(out, "Implements", byType.path("IMPLEMENTS").asLong());
        row(out, "Calls", byType.path("CALLS").asLong());
        row(out, "Type Dependencies", sum(byType, List.of("USES_TYPE", "HAS_PARAMETER", "RETURNS_TYPE", "THROWS")));
        row(out, "Instantiations", byType.path("INSTANTIATES").asLong());
        row(out, "References", byType.path("REFERENCES").asLong());
        row(out, "Overrides", byType.path("OVERRIDES_METHOD").asLong());
        row(out, "Annotations", byType.path("ANNOTATED_WITH").asLong());
        row(out, "Total", m.path("relationships").asLong());
        out.println();
        section(out, "Resolution");
        row(out, "Resolved", m.path("resolvedRelationships").asLong());
        row(out, "Unresolved", m.path("unresolvedRelationships").asLong());
        row(out, "Ambiguous", m.path("ambiguousRelationships").asLong());
        row(out, "Not applicable", m.path("notApplicableRelationships").asLong());
        out.println();
        section(out, "Source Files");
        row(out, "Total", m.path("sourceFiles").asLong());
        row(out, "Parsed", m.path("parsedFiles").asLong());
        row(out, "Failed", m.path("failedFiles").asLong());
        out.println();
        section(out, "OKF Documents");
        row(out, "Total", statistics.documents());
        statistics.documentsByType().forEach((type, count) -> row(out, "  " + type, count));
        row(out, "Broken Links", statistics.brokenLinks());
        out.flush();
        return ExitCodes.OK;
    }

    private static long sum(JsonNode byType, List<String> keys) {
        return keys.stream().mapToLong(k -> byType.path(k).asLong()).sum();
    }

    private static void section(PrintWriter out, String title) {
        out.println(title);
        out.println("-".repeat(title.length()));
    }

    private static void row(PrintWriter out, String label, long value) {
        out.println(String.format("%-24s: %d", label, value));
    }
}
