package com.java2okf.okf;

import com.java2okf.model.JavaExecutable;
import com.java2okf.model.JavaPackage;
import com.java2okf.model.JavaProject;
import com.java2okf.model.JavaType;
import com.java2okf.model.TypeKind;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.stream.Stream;

/**
 * Generates the root {@code index.md} and one {@code index.md} per concept
 * directory. All listings are sorted by qualified name.
 */
public class IndexGenerator {

    public List<OkfDocument> generate(GenerationContext ctx) {
        List<OkfDocument> documents = new ArrayList<>();
        documents.add(root(ctx));
        documents.add(packagesIndex(ctx));
        for (TypeKind kind : TypeKind.values()) {
            List<JavaType> types = typesOf(ctx.project(), kind);
            if (!types.isEmpty() && ctx.settings().isGenerateClassDocuments()) {
                documents.add(typeIndex(ctx, kind, types));
            }
        }
        if (ctx.settings().isGenerateMethodDocuments() && !ctx.project().methods().isEmpty()
                || ctx.settings().isGenerateMethodDocuments() && !ctx.project().constructors().isEmpty()) {
            documents.add(methodsIndex(ctx));
        }
        return documents;
    }

    private OkfDocument root(GenerationContext ctx) {
        JavaProject project = ctx.project();
        LinkRenderer links = ctx.links(DocumentLayout.INDEX);
        MarkdownBuilder md = new MarkdownBuilder();
        md.heading(1, "Java Project Knowledge");
        md.paragraph("Knowledge bundle for " + MarkdownBuilder.code(project.name())
                + ", generated by static analysis. Start from a package or type below and follow the links.");

        md.heading(2, "Contents");
        md.bullet(MarkdownBuilder.link("Packages", DocumentLayout.PACKAGES_DIR + "/" + DocumentLayout.INDEX)
                + " — " + project.packages().size());
        if (ctx.settings().isGenerateClassDocuments()) {
            for (TypeKind kind : TypeKind.values()) {
                long count = project.countTypes(kind);
                if (count > 0) {
                    md.bullet(MarkdownBuilder.link(plural(kind), OkfDocumentType.forKind(kind).directory() + "/" + DocumentLayout.INDEX)
                            + " — " + count);
                }
            }
        }
        if (ctx.settings().isGenerateMethodDocuments()) {
            md.bullet(MarkdownBuilder.link("Methods and constructors", DocumentLayout.METHODS_DIR + "/" + DocumentLayout.INDEX)
                    + " — " + (project.methods().size() + project.constructors().size()));
        }
        if (ctx.settings().isGenerateLogs()) {
            md.bullet(MarkdownBuilder.link("Generation log", DocumentLayout.LOG));
        }
        md.endList();

        md.bulletSection("Packages", project.packages().values().stream()
                .map(p -> links.entity(p.id())).toList());
        if (ctx.settings().isGenerateClassDocuments()) {
            for (TypeKind kind : TypeKind.values()) {
                md.bulletSection(plural(kind), typesOf(project, kind).stream()
                        .map(t -> links.linkTo(t.id(), t.qualifiedName()).orElseThrow()).toList());
            }
        }
        if (ctx.settings().isGenerateMethodDocuments()) {
            md.heading(2, "Methods");
            md.paragraph("Method and constructor documents are listed per declaring type in "
                    + MarkdownBuilder.link("methods/index.md", DocumentLayout.METHODS_DIR + "/" + DocumentLayout.INDEX) + ".");
        }
        return reserved(ctx, DocumentLayout.INDEX, "Java Project Knowledge", md);
    }

    private OkfDocument packagesIndex(GenerationContext ctx) {
        String path = DocumentLayout.PACKAGES_DIR + "/" + DocumentLayout.INDEX;
        LinkRenderer links = ctx.links(path);
        MarkdownBuilder md = new MarkdownBuilder();
        md.heading(1, "Packages");
        for (JavaPackage javaPackage : ctx.project().packages().values()) {
            md.bullet(links.entity(javaPackage.id()) + " — " + javaPackage.typeIds().size() + " types");
        }
        return reserved(ctx, path, "Packages", md);
    }

    private OkfDocument typeIndex(GenerationContext ctx, TypeKind kind, List<JavaType> types) {
        String path = OkfDocumentType.forKind(kind).directory() + "/" + DocumentLayout.INDEX;
        LinkRenderer links = ctx.links(path);
        MarkdownBuilder md = new MarkdownBuilder();
        md.heading(1, plural(kind));
        for (JavaType type : types) {
            md.bullet(links.linkTo(type.id(), type.qualifiedName()).orElseThrow());
        }
        return reserved(ctx, path, plural(kind), md);
    }

    private OkfDocument methodsIndex(GenerationContext ctx) {
        String path = DocumentLayout.METHODS_DIR + "/" + DocumentLayout.INDEX;
        LinkRenderer links = ctx.links(path);
        MarkdownBuilder md = new MarkdownBuilder();
        md.heading(1, "Methods and Constructors");
        List<JavaType> types = ctx.project().types().values().stream()
                .sorted(Comparator.comparing(JavaType::qualifiedName))
                .toList();
        for (JavaType type : types) {
            List<JavaExecutable> executables = Stream.concat(type.constructors().stream(), type.methods().stream())
                    .map(e -> (JavaExecutable) e)
                    .toList();
            if (executables.isEmpty()) {
                continue;
            }
            md.heading(2, type.qualifiedName());
            for (JavaExecutable executable : executables) {
                md.bullet(links.linkTo(executable.id(), DocumentLayout.label(executable.id())).orElseThrow());
            }
        }
        return reserved(ctx, path, "Methods and Constructors", md);
    }

    private static OkfDocument reserved(GenerationContext ctx, String path, String title, MarkdownBuilder md) {
        OkfFrontmatter frontmatter = OkfFrontmatter.of(OkfDocumentType.INDEX, null, title).provenance(ctx.provenance());
        return new OkfDocument(path, frontmatter.build(), md.build());
    }

    private static List<JavaType> typesOf(JavaProject project, TypeKind kind) {
        return project.types().values().stream()
                .filter(t -> t.kind() == kind)
                .sorted(Comparator.comparing(JavaType::qualifiedName))
                .toList();
    }

    static String plural(TypeKind kind) {
        String name = kind.name().charAt(0) + kind.name().substring(1).toLowerCase(Locale.ROOT);
        return kind == TypeKind.CLASS ? "Classes" : name + "s";
    }
}
